thing = input('Digite algo: ')
print(f'Seu tipo primitivo é {type(thing)}')
print(f'Só tem espaços? {thing.isspace()}')
print(f'É númerico? {thing.isnumeric()}')
print(f'É alfabético? {thing.isalpha()}')
print(f'É alfanúmerico? {thing.isalnum()}')
print(f'É maiúsculo? {thing.isupper()}')
print(f'É minúsculo? {thing.islower()}')
print(f'É capitalizado? {thing.istitle()}')