# Faça um programa que leia um número inteiro e mostre na tela o seu sucessor e seu antecessor...
numero = int(input('Digite um número: '))
print(f'O número {numero} tem como: seu antecessor {numero - 1} e seu sucessor {numero + 1}.')